development:
  clients:
    default:
      database: library_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: library_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: <%= ENV['MONGODB_DB'] || 'library_production' %>
      hosts:
        - <%= ENV['MONGODB_HOST'] || 'localhost' %>:<%= ENV['MONGODB_PORT'] || 27017 %>